Fix cargo-vet CI step by use stable rust toolchain (#237)
It's not necessary to use the toolchain specified for puffin. And
`cargo-vet` failed to build with 1.76 toolchain.

### Checklist

* [X] I have read the [Contributor Guide](../CONTRIBUTING.md)
* [X] I have read and agree to the [Code of
Conduct](../CODE_OF_CONDUCT.md)
* [X] I have added a description of my changes and why I'd like them
included in the section below

### Description of Changes

Setup `cargo-vet` CI step to build cargo-vet with `stable` Rust
toolchain.

### Related Issues

Currently `cargo-vet` v0.9.1 failed to build with Rust toolchain v1.73.0
```
error: failed to compile `cargo-vet v0.9.1`, intermediate artifacts can be found at `/tmp/cargo-installc9q6ok`.
To reuse those artifacts with a future compilation, set the environment variable `CARGO_TARGET_DIR` to that path.

Caused by:
  package `cargo-platform v0.1.9` cannot be built because it requires rustc 1.78 or newer, while the currently active rustc version is 1.76.0
```